@identityUrl = https://localhost:5001
@m2mClientId = m2m.client
@m2mClientSecret = 511536EF-F270-4058-80CA-1C89C192F69A

###
# @name ccToken
POST {{identityUrl}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{m2mClientId}}&client_secret={{m2mClientSecret}}&grant_type=client_credentials&scope=scope1

###
@userToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2ODBFQkFGQzYwRjA1OTc2NEIyQTlCMDlGRjQzMzREIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjY3NDE0ODU3LCJpYXQiOjE2Njc0MTQ4NTcsImV4cCI6MTY2NzQxODQ1NywiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMS9yZXNvdXJjZXMiLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJ3ZWItdWkiLCJzdWIiOiIyIiwiYXV0aF90aW1lIjoxNjY3NDE0ODU3LCJpZHAiOiJsb2NhbCIsInNpZCI6IkJCOUU0Mjk4RDFCNDQ1ODgzN0I0RkNGODIxQTlDOEYxIiwianRpIjoiRjFEQUExNTg4Q0RGMzU0OTZFOTNEQTczNjA3NkY0OTgifQ.Bn-D08RGt1nzZbAz1wcuFqdr7lTsPcG3_lkdi0Z3HuN4k0w75Jg-ioAnUjUkgBHV5Fan9jEnd1QZyokN1Hp_fUxyUx_ekicJNMd35R-wJfYYzq9fipbo1-9L7cA47GzdCRv_8wvMd97jj8Sxjx17m5QppLG3lGTuJwrR_G2JejjQK19vzAsII4dpKYdqtXwcsT1SWUnn7yCZGXag1TvgFU3BynPs4lALn31lw_kslnsGS4boHruCGUb1KZOWqcxyBb4rY7aljX2HGPOtjabv8T1-V1-WgpsLG1uOXAnXHswuwn_sYJ5p3cn36VpeqzEXfyKSVLUNnrQY00RlsahxPQ
POST {{identityUrl}}/connect/userinfo
Authorization: Bearer {{userToken}}

###
@externalToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNMd0NkZWhiN00tM0lIQUgzdG5RQiJ9.eyJpc3MiOiJodHRwczovL2Rldi10dWJob3l3ZzZhMHUzemNvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MzdiMTU4MDliOWM0ZmVmZmJmNmUwOWEiLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLnBhcnRuZXIuZXh0ZXJuYWwubG9jYWwiLCJodHRwczovL2Rldi10dWJob3l3ZzZhMHUzemNvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2Njk3NjA1NzksImV4cCI6MTY2OTg0Njk3OSwiYXpwIjoiS2ZBd3hRZTFhaVJ5QlFoTTZQVFBHMDBxa2loYWliS3AiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIHJlYWQ6Y2FsZW5kYXIifQ.gSHjcbGCYT5lvVQRO1FdOasoEbOLQ-za9BNEsN_yv8iM0zlWIaruwEYfmpn6gxHApv6A9oxMAwfAEXk-QJC0dTpquQ6Uy0yNbT-LoQtR2FZ0o37M9BEMlSyTNzNqQfStamkwG-cEsHrLc2s8hb751DhxbsuTLjffOjVR2FFeJBI6FUsEw8tHqI0h5evbjF0vtSrADM9FcWBh9Qs6uEowwOJRcqlzm2nRTqa620Le1B9o184DghmyTm5i8GLwPOi06xFk0g6Kagsy82FF4MdNm7Bxwz79JB3LY0uwf6yK5bjwnCIuXzcetNuipcrALKBlM5UoN1oOyGREqWW9OSiYtw
GET https://localhost:7217/Calendar
Authorization: Bearer {{externalToken}}
